version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: clouddw:latest
    env_file:
      - .env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_DEFAULT_REGION}
    container_name: clouddw
    tty: true
    stdin_open: true
    command: bash